/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Workshop.view;

import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Pradip
 */
public class carMgmnt extends javax.swing.JPanel {

    /**
     * Creates new form carMgmnt
     */
    int var=0;
    public carMgmnt(int var) throws SQLException, ParseException {
        initComponents();
        this.var=var;
        if(var==1){
           tab.add(new searchCar(var), "Search Car"); 
           
        }
       else if(var==2){
        tab.add(new addCar(), "Add Car");
        tab.add(new addModel(), "Add Model"); 
        tab.add(new searchCar(var), "Search Car");
        }
        else if(var==3){
           tab.add(new searchCar(var), "Search Car"); 
        }
        else if(var==4){
            tab.add(new purchaseInventory(), "Sell");
        tab.add(new customerBill(),"Billing");
        tab.add(new searchCar(var), "Search Car"); 
        }
        else {
            JOptionPane.showMessageDialog(null, "Something went wrong");
        }
        
        
        this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car Management", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
}
