/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Workshop.view;

import Workshop.modules.Customer;
import Workshop.modules.CustomerCar;
import Workshop.modules.Transaction;
import Workshop.utils.TableManager;
import WorkshopController.CarController;
import WorkshopController.CustomerController;
import WorkshopController.TransactionController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pradip
 */
public class customerBill extends javax.swing.JPanel {

    /**
     * Creates new form customerBill
     */
    int id=0;
    Date date=null;DefaultTableModel data=null;
    public customerBill() throws SQLException, ParseException {
        initComponents();
        loadCombo();
        
    }
    public void loadCombo() throws SQLException{
        CustomerController cus=new CustomerController();
        ResultSet rs=cus.getCustomers();
        while(rs.next()){
            String fname=rs.getString("fname");
            String lname=rs.getString("lname");
            cmb_name.addItem(fname+" "+lname);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_details = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_vat = new javax.swing.JTextField();
        txt_discount = new javax.swing.JTextField();
        btn_prepare = new javax.swing.JButton();
        cmb_name = new javax.swing.JComboBox<>();
        txt_date = new javax.swing.JTextField();

        jLabel1.setText("Name");

        jLabel3.setText("Date");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("All Star Traders");

        tbl_details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_details);

        jLabel5.setText("Total");

        lbl_total.setText("lbl_total");

        jLabel7.setText("Enter Vat Percent");

        jLabel8.setText("Enter Discount Percent");

        btn_prepare.setText("Prepare");
        btn_prepare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prepareActionPerformed(evt);
            }
        });

        cmb_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_nameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_vat, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_total)
                                        .addGap(43, 43, 43))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(btn_prepare))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(186, 186, 186)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_name, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 378, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_total))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_vat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btn_prepare)
                .addGap(89, 89, 89))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_nameMouseClicked
        try {
            // TODO add your handling code here:
            String fullname=String.valueOf(cmb_name.getSelectedItem());
            String arr[]=fullname.split(" ", 2);
            String fname=arr[0];
            String lname=arr[1];
            Customer cs=new Customer();
            cs.setFname(fname);
            cs.setLname(lname);
            
            CustomerController cus=new CustomerController();
            int idd=cus.getCustomerId(cs);
            cs.setId(idd);
            
             SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
           Date dat=sdf.parse(txt_date.getText());
           CustomerCar cusc=new CustomerCar();
           cusc.setDate(dat);
           cusc.setCustomerId(cs);
           CarController car=new CarController();
           ResultSet rs=car.getPrice(cusc);
           DefaultTableModel data=TableManager.buildDataTable(rs);
           tbl_details.setModel(data);
           this.data=data;
           
          for(int i = 0; i < tbl_details.getRowCount(); i++){
        float total = 0;
        float Amount =Float.valueOf(String.valueOf(tbl_details.getValueAt(i, 2)));
        total = Amount+total;
        lbl_total.setText(String.valueOf(total));
          }
           
        } catch (SQLException ex) {
            Logger.getLogger(customerBill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(customerBill.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_cmb_nameMouseClicked

    private void btn_prepareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prepareActionPerformed
        try {
            // TODO add your handling code here:
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            Date bill=sdf.parse(txt_date.getText());
            
            String fullname=String.valueOf(cmb_name.getSelectedItem());
            String arr[]=fullname.split(" ", 2);
            String fname=arr[0];
            String lname=arr[1];
            Customer cs=new Customer();
            cs.setFname(fname);
            cs.setLname(lname);
            
            CustomerController cus=new CustomerController();
            int idd=cus.getCustomerId(cs);
            Transaction t=new Transaction();
            t.setDate(bill);
            t.setType("customer");
            t.setTypeId(id);
            t.setStatus("received");
            
            float total=Float.valueOf(lbl_total.getText());
            int vat=Integer.parseInt(txt_vat.getText());
            int disc=Integer.parseInt(txt_discount.getText());
            float vatAmount=total+(vat/100*total);
            float finalAmount=vatAmount-(disc/100*vatAmount);
            
            t.setAmount(finalAmount);
            
            TransactionController tc=new TransactionController();
            int done=tc.doEntry(t);
            if(done!=0){
                finalCustomerBill bc=new finalCustomerBill(data,fullname,bill,vat,disc,finalAmount);
               bc.setVisible(true);
            }
            
            
        } catch (ParseException ex) {
            Logger.getLogger(customerBill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(customerBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_prepareActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_prepare;
    private javax.swing.JComboBox<String> cmb_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTable tbl_details;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_discount;
    private javax.swing.JTextField txt_vat;
    // End of variables declaration//GEN-END:variables
}
