/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Workshop.view;

import java.awt.Desktop;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pradip
 */
public class DashBoard1 extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard1
     */
    int var=0;
    String fname=null;
    String lname=null;
    public DashBoard1(int var, String fname, String lname) {
        initComponents();
        this.var=var;
        this.fname=fname;
        this.lname=lname;
       lbl_lname.setText(lname);
       lbl_fname.setText(fname);
        if(var==1){
            
            lbl_pos.setText("Receptionist");
            supp_menu.setVisible(false);
        }
        else if(var==2){
            supp_menu.setVisible(true);
            lbl_pos.setText("Admin");
        }
        else if(var==3){
           
            lbl_pos.setText("Manager");
        }
        else if(var==4){
            supp_menu.setVisible(true);
            lbl_pos.setText("Accountant");
        }
        else{
          supp_menu.setVisible(false);  
        }
        this.setExtendedState(this.MAXIMIZED_BOTH);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        lbl_fname = new javax.swing.JLabel();
        lbl_lname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_pos = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        supp_menu = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();

        jMenu4.setText("jMenu4");

        jMenu6.setText("jMenu6");

        jMenu9.setText("jMenu9");

        jMenu10.setText("jMenu10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbl_fname.setText("fname");
        getContentPane().add(lbl_fname);
        lbl_fname.setBounds(330, 180, 120, 15);

        lbl_lname.setText("lname");
        getContentPane().add(lbl_lname);
        lbl_lname.setBounds(520, 180, 140, 15);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Welcome to CarGiant Management System");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 100, 344, 22);

        lbl_pos.setText("Position");
        getContentPane().add(lbl_pos);
        lbl_pos.setBounds(340, 240, 150, 15);

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setForeground(new java.awt.Color(102, 102, 255));
        jMenuBar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("Customer Controller");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setText("Staff Controller");
        jMenu2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(0, 0, 0));
        jMenu3.setText("Car Controller");
        jMenu3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        supp_menu.setForeground(new java.awt.Color(0, 0, 0));
        supp_menu.setText("Supplier Controller");
        supp_menu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        supp_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supp_menuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                supp_menuMousePressed(evt);
            }
        });
        jMenuBar1.add(supp_menu);

        jMenu7.setForeground(new java.awt.Color(0, 0, 0));
        jMenu7.setText("Logout");
        jMenu7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu7MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        jMenu8.setBackground(new java.awt.Color(51, 51, 51));
        jMenu8.setForeground(new java.awt.Color(0, 0, 0));
        jMenu8.setText("Exit");
        jMenu8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu8MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        jMenu11.setBackground(new java.awt.Color(51, 51, 51));
        jMenu11.setForeground(new java.awt.Color(0, 0, 0));
        jMenu11.setText("Help");
        jMenu11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenu11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu11MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        try {
            // TODO add your handling code here:
            this.setContentPane(new customermgmnt(var));
            this.validate();
        } catch (SQLException ex) {
            Logger.getLogger(DashBoard1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        try {
            // TODO add your handling code here:
            this.setContentPane(new carMgmnt(var));
        } catch (SQLException ex) {
            Logger.getLogger(DashBoard1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(DashBoard1.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.validate();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu8MousePressed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            this.setContentPane(new staffMgmnt(var));
            this.validate();
        } catch (SQLException ex) {
            Logger.getLogger(DashBoard1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(DashBoard1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DashBoard1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu2MousePressed

    private void jMenu7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MousePressed
        // TODO add your handling code here:
        LoginFrame lg=new LoginFrame();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu7MousePressed

    private void supp_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supp_menuMousePressed
        try {
            // TODO add your handling code here:]
            
            this.setContentPane(new SupplierManagement(var));
        } catch (SQLException ex) {
            Logger.getLogger(DashBoard1.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.validate();
    }//GEN-LAST:event_supp_menuMousePressed

    private void jMenu11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu11MousePressed
        // TODO add your handling code here:
        File pdf = new File("D:\\CarWorkShop_Management\\Project\\Java Files\\WorkshopManagement\\UserManual\\User Manual.pdf");
        try {
            Desktop.getDesktop().open(pdf);
        } catch (IOException ex) {
            Logger.getLogger(DashBoard1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu11MousePressed

    private void supp_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supp_menuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_supp_menuMouseClicked

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl_fname;
    private javax.swing.JLabel lbl_lname;
    private javax.swing.JLabel lbl_pos;
    private javax.swing.JMenu supp_menu;
    // End of variables declaration//GEN-END:variables
}
