/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Workshop.view;

import WorkshopController.TransactionController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pradip
 */
public class profitLoss extends javax.swing.JPanel {

    /**
     * Creates new form profitLoss
     */
    public profitLoss() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmb_month = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sup = new javax.swing.JLabel();
        staff = new javax.swing.JLabel();
        cus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tot = new javax.swing.JLabel();

        jLabel1.setText("Select Month ");

        cmb_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Janauary", "2 Febrauary", "3  March", "4 April", "5 May", "6 June", "7 July", "8 August", "9 September", "10 October", "11 November", "12 December", " " }));
        cmb_month.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmb_monthMousePressed(evt);
            }
        });

        jLabel2.setText("Total Paid to Supplier");

        jLabel3.setText("Total Salary Paid to Staffs");

        jLabel4.setText("Total Received from Customer");

        sup.setText("jLabel5");

        staff.setText("jLabel6");

        cus.setText("jLabel7");

        jLabel5.setText("Net Worth of this month");

        tot.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(staff))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sup))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(99, 99, 99)
                        .addComponent(cmb_month, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tot)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sup))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(staff))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cus))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tot)
                    .addComponent(jLabel5))
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_monthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_monthMousePressed
        try {
            // TODO add your handling code here:
            int month=cmb_month.getSelectedIndex();
            int month_no=month+1;
            TransactionController trans=new TransactionController();
            ResultSet rs=trans.getCusTrans(month_no);
            float cus_total=0;
            while(rs.next()){
               float amount= (float)rs.getInt("amount");
               cus_total+=amount;
            }
            ResultSet rss=trans.getStaffTrans(month_no);
           float sta_total=0;
            while(rss.next()){
               float amount= (float) rss.getInt("amount");
               sta_total+=amount;
            }
            
            ResultSet done=trans.getSupplierTrans(month_no);
            float sup_total=0;
            while(done.next()){
               float amount= (float)done.getInt("amount");
               sup_total+=amount;
            }
            
            sup.setText(String.valueOf(sup_total));
           staff.setText(String.valueOf(sta_total));
            cus.setText(String.valueOf(cus_total));
           float result=sup_total+sta_total-cus_total;
           tot.setText(String.valueOf(result));
        } catch (SQLException ex) {
            Logger.getLogger(profitLoss.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmb_monthMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_month;
    private javax.swing.JLabel cus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel staff;
    private javax.swing.JLabel sup;
    private javax.swing.JLabel tot;
    // End of variables declaration//GEN-END:variables
}
