/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Workshop.view;

import Workshop.modules.CarModel;
import Workshop.modules.CarPart;
import Workshop.modules.Customer;
import Workshop.modules.CustomerCar;
import WorkshopController.CarController;
import WorkshopController.CustomerController;
import WorkshopController.OtherController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pradip
 */
public class purchaseInventory extends javax.swing.JPanel {

    /**
     * Creates new form purchaseInventory
     */
    String date;
    int cus_id=0;
    public purchaseInventory() throws SQLException, ParseException {
        initComponents();
        Calendar cal=Calendar.getInstance();
        SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
        
        String datee=sdf.format(cal.getTime());
        lbl_date.setText("Date :"+datee);
         this.date=datee;
        loadCombo();
    }
    
    public void loadCar() throws SQLException{
     String model=String.valueOf(cmb_model.getSelectedItem()); 
     String type=String.valueOf(cmb_type.getSelectedItem());
     CarModel cm=new CarModel();
     cm.setModel(model);
     CarPart car=new CarPart();
     car.setType(type);
     car.setModelId(cm);
     
     CarController cr=new CarController();
     tbl_car.setModel(cr.buildCarTable(car));
     
    }
    
    public void loadCombo() throws SQLException{
        CustomerController cus=new CustomerController();
        ResultSet rs=cus.getCustomers();
        while(rs.next()){
            String fname=rs.getString("fname");
            String lname=rs.getString("lname");
            cmb_customer.addItem(fname+" "+lname);
        }
        CarController car=new CarController();
        ResultSet rss=car.getModel();
        while(rss.next()){
            cmb_model.addItem(rss.getString("model"));
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmb_customer = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmb_model = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmb_type = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_car = new javax.swing.JTable();
        btn_asign = new javax.swing.JButton();
        lbl_date = new javax.swing.JLabel();

        jLabel1.setText("Select the Customer");

        cmb_customer.setToolTipText("--Select Customer Name--");

        jLabel2.setText("Select the model of Inventory");

        jLabel3.setText("Select the type of inventory");

        cmb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "car", "part" }));
        cmb_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_typeActionPerformed(evt);
            }
        });

        tbl_car.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Price", "Available Unit"
            }
        ));
        jScrollPane1.setViewportView(tbl_car);

        btn_asign.setText("Assign");
        btn_asign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_asignActionPerformed(evt);
            }
        });

        lbl_date.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addGap(221, 221, 221)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_model, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_type, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_date)
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(btn_asign))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmb_customer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_model, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmb_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btn_asign)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_typeActionPerformed
        try {
            // TODO add your handling code here:
            loadCar();
        } catch (SQLException ex) {
            Logger.getLogger(purchaseInventory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmb_typeActionPerformed

    private void btn_asignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_asignActionPerformed
      if(tbl_car.getSelectedRow()!=-1){
        try {
            // TODO add your handling code here:
            String fullname=String.valueOf(cmb_customer.getSelectedItem());
            String arr[]=fullname.split(" ", 2);
            String fname=arr[0];
            String lname=arr[1];
            Customer cs=new Customer();
            cs.setFname(fname);
            cs.setLname(lname);
            
            CustomerController cus=new CustomerController();
            int idd=cus.getCustomerId(cs);
           cs.setId(idd);
           this.cus_id=idd;
           
           int memId=tbl_car.getSelectedRow();
           int car_id=(Integer) tbl_car.getValueAt(memId, 0);
           CarPart cr=new CarPart();
           cr.setId(car_id);
           
           CustomerCar cusc=new CustomerCar();
           cusc.setCarId(cr);
           cusc.setCustomerId(cs);
           SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
           Date dat=sdf.parse(date);
           cusc.setDate(dat);
            System.out.println(dat);
           
           OtherController oth =new OtherController();
           int done=oth.insertPurchase(cusc);
           if(done!=0){
               JOptionPane.showMessageDialog(null, "Successful");
              
                       
           }
           else
           {
            JOptionPane.showMessageDialog(null, "UnSuccessful");   
           }
            
        } catch (SQLException ex) {
            Logger.getLogger(purchaseInventory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
              Logger.getLogger(purchaseInventory.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
      else{
          JOptionPane.showMessageDialog(null, "Please Select a row from table");      }
    }//GEN-LAST:event_btn_asignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_asign;
    private javax.swing.JComboBox<String> cmb_customer;
    private javax.swing.JComboBox<String> cmb_model;
    private javax.swing.JComboBox<String> cmb_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JTable tbl_car;
    // End of variables declaration//GEN-END:variables
}
