/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Workshop.view;

import Workshop.modules.Staff;
import Workshop.modules.Transaction;
import WorkshopController.StaffController;
import WorkshopController.TransactionController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pradip
 */
public class salaryStatement extends javax.swing.JPanel {

    /**
     * Creates new form salaryStatement
     */
    Date dat=null;
    int staff_id=0;
    float amount=0;
    public salaryStatement() throws SQLException, ParseException {
        initComponents();
         Calendar cal=Calendar.getInstance();
        SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
        String datee=sdf.format(cal.getTime());
        dat=sdf.parse(datee);
        loadCombo();
    }
    
    public void loadCombo() throws SQLException{
      StaffController staf=new StaffController();  
      ResultSet rs=staf.getStaffs();
     while(rs.next()){
         String fname=rs.getString("fname");
         String lname=rs.getString("lname");
         cmbStaff.addItem(fname+" "+lname);
     }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbStaff = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmb_month = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lbl_type = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_wage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_days = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        btn_pay = new javax.swing.JButton();

        jLabel1.setText("Seleect The Staff");

        jLabel2.setText("Select month");

        cmb_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        cmb_month.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmb_monthMousePressed(evt);
            }
        });

        jLabel3.setText("Post of Staff");

        lbl_type.setText("type");

        jLabel5.setText("Daily Payment of Staff");

        lbl_wage.setText("Wage");

        jLabel7.setText("Total present days of this month");

        lbl_days.setText("Present");

        jLabel9.setText("Total Salary of this Month");

        lbl_total.setText("total");

        btn_pay.setText("Pay");
        btn_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_payActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbStaff, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmb_month, 0, 83, Short.MAX_VALUE)
                        .addComponent(lbl_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbl_days, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_wage, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(lbl_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(169, 169, 169))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(btn_pay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmb_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_type))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbl_wage)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_days))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbl_total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_pay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_monthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_monthMousePressed
        try {
            // TODO add your handling code here:
            float wage=0;
            String type=null;
            
            String fullname=String.valueOf(cmbStaff.getSelectedItem());
            String arr[]=fullname.split(" ", 2);
            String fname=arr[0];
            String lname=arr[1];
            Staff st=new Staff();
            st.setFname(fname);
            st.setLname(lname);
            StaffController sta=new StaffController();
            int id=sta.getId(st);
            this.staff_id=id;
            int month1=cmb_month.getSelectedIndex();
            int month=month1+1;
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            Date start=sdf.parse("2017-"+month+"-1");
            Date end=sdf.parse("2017-"+month+"-28");
            int count=sta.countDays(start, end, id);
            st.setId(id);
            ResultSet rs=sta.getTypeDetails(st);
            while(rs.next()){
               wage=Float.valueOf(rs.getInt("daily_wage"));
               type=rs.getString("staff_type");
            }
            
            lbl_days.setText(String.valueOf(count));
            lbl_wage.setText(String.valueOf(wage));
            lbl_type.setText(type);
            float total=wage*count;
            lbl_total.setText(String.valueOf(total));
            this.amount=total;
        } catch (SQLException ex) {
            Logger.getLogger(salaryStatement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(salaryStatement.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cmb_monthMousePressed

    private void btn_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_payActionPerformed
        try {
            // TODO add your handling code here:
            Transaction tc=new Transaction();
            tc.setDate(dat);
            tc.setType("staff");
            tc.setTypeId(staff_id);
            tc.setAmount(amount);
            tc.setStatus("paid");
            
            TransactionController tran=new TransactionController();
            int done=tran.doEntry(tc);
            if(done!=0){
                JOptionPane.showMessageDialog(null, "Successfully paid");
            }
            else{
              JOptionPane.showMessageDialog(null, "Cannot Pay");  
            }
        } catch (SQLException ex) {
            Logger.getLogger(salaryStatement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_payActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_pay;
    private javax.swing.JComboBox<String> cmbStaff;
    private javax.swing.JComboBox<String> cmb_month;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_days;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_type;
    private javax.swing.JLabel lbl_wage;
    // End of variables declaration//GEN-END:variables
}
