/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Workshop.view;

import Workshop.modules.Staff;
import Workshop.modules.StaffType;
import Workshop.utils.TableManager;
import WorkshopController.AttendenceController;
import WorkshopController.OtherController;
import WorkshopController.StaffController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pradip
 */
public class searchStaff extends javax.swing.JPanel {

    /**
     * Creates new form searchStaff
     */
    int id=0;
    int var=0;
    public searchStaff(int var) {
        initComponents();
        if(var==4){
           upp.setVisible(false);
            del.setVisible(false);
        }else if(var==1){
            upp.setVisible(true);
            del.setVisible(false);
        }
        else{
           upp.setVisible(true);
            del.setVisible(true); 
        }
        lbl_fname.setVisible(false);
        lbl_lname.setVisible(false);
        lbl_address.setVisible(false);
        lbl_contact.setVisible(false);
        lbl_staff.setVisible(false);;
        txt_fname.setVisible(false);
        txt_lname.setVisible(false);
        txt_add.setVisible(false);
        txt_contact.setVisible(false);
        cmb_satff.setVisible(false);
        btn_update.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmb_type = new javax.swing.JComboBox<>();
        txt_field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_staff = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        upp = new javax.swing.JButton();
        del = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_att = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        lbl_fname = new javax.swing.JLabel();
        lbl_lname = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        lbl_contact = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        txt_add = new javax.swing.JTextField();
        txt_contact = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        lbl_staff = new javax.swing.JLabel();
        cmb_satff = new javax.swing.JComboBox<>();

        jLabel1.setText("Search by");

        cmb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff Type", "Staff Name" }));

        txt_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_fieldKeyTyped(evt);
            }
        });

        tbl_staff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Staff Name", "Address", "Type", "Contact"
            }
        ));
        jScrollPane1.setViewportView(tbl_staff);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Details of staff");

        upp.setText("Update");
        upp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uppActionPerformed(evt);
            }
        });

        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        jButton3.setText("View Attendence History");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Attendence History of Selected Staff");

        tbl_att.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Status"
            }
        ));
        jScrollPane2.setViewportView(tbl_att);

        jButton4.setText("Refresh table");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lbl_fname.setText("Firstname");

        lbl_lname.setText("last Name");

        lbl_address.setText("Address");

        lbl_contact.setText("Contact");

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        lbl_staff.setText("Staff Type");

        cmb_satff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_satffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(upp)
                                .addGap(37, 37, 37)
                                .addComponent(del)
                                .addGap(35, 35, 35)
                                .addComponent(jButton3)
                                .addGap(36, 36, 36)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_fname)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(btn_update)))))
                        .addGap(99, 99, 99))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(61, 61, 61)
                                            .addComponent(cmb_type, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(88, 88, 88)
                                            .addComponent(txt_field, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbl_address)
                                                .addComponent(lbl_staff))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txt_contact)
                                                .addComponent(txt_add)
                                                .addComponent(cmb_satff, 0, 88, Short.MAX_VALUE))
                                            .addGap(247, 247, 247)))
                                    .addComponent(lbl_contact)
                                    .addComponent(lbl_lname))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmb_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(upp)
                    .addComponent(del)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fname)
                    .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_lname)
                            .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_address)
                            .addComponent(txt_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btn_update)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_contact)
                    .addComponent(txt_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_staff)
                    .addComponent(cmb_satff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fieldKeyTyped
        // TODO add your handling code here:
        int index=cmb_type.getSelectedIndex();
        String name=txt_field.getText();
        if(index==0){
            try {
                StaffType stt=new StaffType();
                stt.setStaffType(name);
                StaffController st=new StaffController();
                tbl_staff.setModel(st.buildStaffTable(stt));
            } catch (SQLException ex) {
                Logger.getLogger(searchStaff.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(index==1){
            try {
                Staff st=new Staff();
                st.setFname(name);
                StaffController staf=new StaffController();
                tbl_staff.setModel(TableManager.buildDataTable(staf.getStaff(st)));
            } catch (SQLException ex) {
                Logger.getLogger(searchStaff.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txt_fieldKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(tbl_staff.getSelectedRow()!=-1){
            int memId=tbl_staff.getSelectedRow();
            int id=(Integer) tbl_staff.getValueAt(memId,0);
            Staff stt=new Staff();
            stt.setId(id);
            
            AttendenceController at=new AttendenceController();
            try {
                tbl_att.setModel(TableManager.buildDataTable(at.getAttendence(stt)));
            } catch (SQLException ex) {
                Logger.getLogger(searchStaff.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        if(tbl_staff.getSelectedRow()!=-1){
            try {
                int memId=tbl_staff.getSelectedRow();
                int id=(Integer) tbl_staff.getValueAt(memId,0);
                Staff stt=new Staff();
                stt.setId(id);
                StaffController staf=new StaffController();
                int done=staf.deleteStaff(stt);
                if(done!=0){
                    JOptionPane.showMessageDialog(null," Selected Staff is deleted");
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(searchStaff.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_delActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int index=cmb_type.getSelectedIndex();
        String name=txt_field.getText();
        if(index==0){
            try {
                StaffType stt=new StaffType();
                stt.setStaffType(name);
                StaffController st=new StaffController();
                tbl_staff.setModel(st.buildStaffTable(stt));
            } catch (SQLException ex) {
                Logger.getLogger(searchStaff.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(index==1){
            try {
                Staff stat=new Staff();
                stat.setFname(name);
                StaffController staf=new StaffController();
                tbl_staff.setModel(TableManager.buildDataTable(staf.getStaff(stat)));
            } catch (SQLException ex) {
                Logger.getLogger(searchStaff.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cmb_satffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_satffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_satffActionPerformed

    private void uppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uppActionPerformed
        // TODO add your handling code here:
        if(tbl_staff.getSelectedRow()!=-1){
            try {
                lbl_fname.setVisible(true);
                lbl_lname.setVisible(true);
                lbl_address.setVisible(true);
                lbl_contact.setVisible(true);
                lbl_staff.setVisible(true);;
                txt_fname.setVisible(true);
                txt_lname.setVisible(true);
                txt_add.setVisible(true);
                txt_contact.setVisible(true);
                cmb_satff.setVisible(true);
                btn_update.setVisible(true);
                
                int member=tbl_staff.getSelectedRow();
                int idd=(Integer) tbl_staff.getValueAt(member, 0);
                this.id=idd;
                String fname=String.valueOf(tbl_staff.getValueAt(member, 1));
                String lname=String.valueOf(tbl_staff.getValueAt(member, 2));
                String address=String.valueOf(tbl_staff.getValueAt(member, 3));
                int contact=Integer.parseInt(String.valueOf(tbl_staff.getValueAt(member, 4)));
                String type=String.valueOf(tbl_staff.getValueAt(member, 5));
                
                txt_fname.setText(fname);
                txt_lname.setText(lname);
                txt_add.setText(address);
                txt_contact.setText(String.valueOf(contact));
                
                StaffController st=new StaffController();
                ResultSet rs=st.getAllType();
                while(rs.next()){
                    String name=rs.getString("staff_type");
                    cmb_satff.addItem(name);
                }
                cmb_satff.setSelectedItem(type);
            } catch (SQLException ex) {
                Logger.getLogger(searchStaff.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_uppActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
            // TODO add your handling code here:
            String fname=txt_fname.getText();
            String lname=txt_lname.getText();
            String address=txt_add.getText();
            int contact=Integer.parseInt(txt_contact.getText());
            String type=String.valueOf(cmb_satff.getSelectedItem());
            
            StaffType stt=new StaffType();
            stt.setStaffType(type);
            OtherController staf=new OtherController();
            int st_id=staf.getType(stt);
            stt.setId(st_id);
            
            Staff staff=new Staff();
            staff.setFname(fname);
            staff.setLname(lname);
            staff.setAddress(address);
            staff.setContact(contact);
            staff.setStaffTypeId(stt);
            staff.setId(id);
            
            StaffController sta=new StaffController();
            int done=sta.updateStaff(staff);
            if(done!=0){
                JOptionPane.showMessageDialog(null, "succesful");
                txt_add.setText("");
                txt_contact.setText("");
                txt_fname.setText("");
                txt_lname.setText("");
            }
            else{
               JOptionPane.showMessageDialog(null, "something went wrong"); 
            }
        } catch (SQLException ex) {
            Logger.getLogger(searchStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_satff;
    private javax.swing.JComboBox<String> cmb_type;
    private javax.swing.JButton del;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_contact;
    private javax.swing.JLabel lbl_fname;
    private javax.swing.JLabel lbl_lname;
    private javax.swing.JLabel lbl_staff;
    private javax.swing.JTable tbl_att;
    private javax.swing.JTable tbl_staff;
    private javax.swing.JTextField txt_add;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_field;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JButton upp;
    // End of variables declaration//GEN-END:variables
}
