/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Workshop.view;

import Workshop.modules.CarPart;
import Workshop.utils.TableManager;
import WorkshopController.CarController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pradip
 */
public class searchCar extends javax.swing.JPanel {

    /**
     * Creates new form searchCar
     */
    int id=0;
    int var=0;
    public searchCar(int var) {
        initComponents();
        this.var=var;
        if(var==2){
            upp.setVisible(true);
            del.setVisible(true);
        }
        else{
           upp.setVisible(false);
            del.setVisible(false); 
        }
        lbl_name.setVisible(false);
        lbl_price.setVisible(false);
        lvl_av.setVisible(false);
        txt_part.setVisible(false);
        txt_av.setVisible(false);
        txt_price.setVisible(false);
        btn_update.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmb_type = new javax.swing.JComboBox<>();
        txt_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_car = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        upp = new javax.swing.JButton();
        del = new javax.swing.JButton();
        lbl_name = new javax.swing.JLabel();
        lbl_price = new javax.swing.JLabel();
        txt_part = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        lvl_av = new javax.swing.JLabel();
        txt_av = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();

        jLabel1.setText("Search by");

        cmb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "model", "name" }));

        txt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nameKeyTyped(evt);
            }
        });

        tbl_car.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_car);

        jLabel2.setText("Details of car");

        upp.setText("Update");
        upp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uppActionPerformed(evt);
            }
        });

        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        lbl_name.setText("Name");

        lbl_price.setText("Price");

        lvl_av.setText("Available Units");

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addGap(91, 91, 91)
                        .addComponent(cmb_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(upp)
                        .addGap(73, 73, 73)
                        .addComponent(del)
                        .addGap(178, 178, 178))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_name)
                            .addComponent(lbl_price)
                            .addComponent(lvl_av, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_price, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(txt_part)
                            .addComponent(txt_av))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btn_update)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upp)
                    .addComponent(del)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name)
                    .addComponent(txt_part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lbl_price))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_av, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvl_av))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btn_update)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyTyped
        try {
            // TODO add your handling code here:
            int index=cmb_type.getSelectedIndex();
            String name =txt_name.getText();
            CarController car=new CarController();
            ResultSet rs=car.getAllCar(index, name);
            tbl_car.setModel(TableManager.buildDataTable(rs));
            
        } catch (SQLException ex) {
            Logger.getLogger(searchCar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_nameKeyTyped

    private void uppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uppActionPerformed
        // TODO add your handling code here:
        if(tbl_car.getSelectedRow()!=-1){
        lbl_name.setVisible(true);
        lbl_price.setVisible(true);
        lvl_av.setVisible(true);
        txt_part.setVisible(true);
        txt_av.setVisible(true);
        txt_price.setVisible(true);
        btn_update.setVisible(true);
        
        int member=tbl_car.getSelectedRow();
        int idd=(Integer) tbl_car.getValueAt(member, 0);
        this.id=idd;
        txt_part.setText(String.valueOf(tbl_car.getValueAt(member, 1)));
        txt_av.setText(String.valueOf(tbl_car.getValueAt(member, 3)));
        txt_price.setText(String.valueOf(tbl_car.getValueAt(member, 4)));
        }
        
    }//GEN-LAST:event_uppActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
            // TODO add your handling code here:
            String name=txt_part.getText();
            int ava=Integer.parseInt(txt_av.getText());
            float price=Float.parseFloat(txt_price.getText());
            
            CarPart cp=new CarPart();
            cp.setName(name);
            cp.setAvailableUnit(ava);
            cp.setPrice(price);
            cp.setId(id);
            
            CarController car=new CarController();
            int done=car.updateCar(cp);
            if(done!=0){
                JOptionPane.showMessageDialog(null,"Success");
                txt_av.setText("");
                txt_part.setText("");
                txt_price.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(searchCar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
       if(tbl_car.getSelectedRow()!=-1){
           try {
               int member=tbl_car.getSelectedRow();
               int car_id=(Integer) tbl_car.getValueAt(member, 0);
               CarPart cpp=new CarPart();
               cpp.setId(car_id);
               
               CarController car=new CarController();
               int done=car.deleteCar(cpp);
               if(done!=0){
                   JOptionPane.showMessageDialog(null, "Selected Car is deleted");
                   
                    int index=cmb_type.getSelectedIndex();
            String name =txt_name.getText();
            CarController carr=new CarController();
            ResultSet rs=carr.getAllCar(index, name);
            tbl_car.setModel(TableManager.buildDataTable(rs));
               }
               else{
                 JOptionPane.showMessageDialog(null, "Something went wrong");  
               }
           } catch (SQLException ex) {
               Logger.getLogger(searchCar.class.getName()).log(Level.SEVERE, null, ex);
           }
           
       }
    }//GEN-LAST:event_delActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_type;
    private javax.swing.JButton del;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_price;
    private javax.swing.JLabel lvl_av;
    private javax.swing.JTable tbl_car;
    private javax.swing.JTextField txt_av;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_part;
    private javax.swing.JTextField txt_price;
    private javax.swing.JButton upp;
    // End of variables declaration//GEN-END:variables
}
