/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Workshop.view;

import Workshop.modules.Customer;
import Workshop.modules.Services;
import Workshop.modules.Staff;
import Workshop.modules.StaffType;
import WorkshopController.CustomerController;
import WorkshopController.StaffController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pradip
 */
public class StaffSelector extends javax.swing.JFrame{

    /** Creates new form StaffSelector */
    int id=0;
    String Service=null;
    StaffController staf=new StaffController();
    Customer cs=new Customer();
    public StaffSelector(int idd, String serve, Customer css ) {
        try {
            this.id=idd;
            this.cs=css;
            if(serve.equals("purchase")){
                Service="salesmen";
            }
            else if(serve.equals("repair")){
                Service="mechanic";
            }
            else if(serve.equals("conselling")){
                Service="counselor";
            }
            
            StaffType sta=new StaffType();
            sta.setStaffType(Service);
            initComponents();
            loadStaffs(sta);
        } catch (SQLException ex) {
            Logger.getLogger(StaffSelector.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void loadStaffs(StaffType sta) throws SQLException{
        tbl_staff.setModel(staf.buildStaffTable(sta));
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_staff = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_assign = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_staff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_staff);

        jLabel1.setText("List Of Staff");

        btn_assign.setText("Assign");
        btn_assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_assignActionPerformed(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_assign)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_assign))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_assignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_assignActionPerformed
        // TODO add your handling code here:
        if(tbl_staff.getSelectedRow()!=-1){
            try {
                int member=tbl_staff.getSelectedRow();
                int idd=(Integer)tbl_staff.getValueAt(member, 0);
                String name=String.valueOf(tbl_staff.getValueAt(member, 1));
                Staff st=new Staff();
                st.setId(idd);
                cs.setStaffId(st);
                
                Services sc=new Services();
                sc.setId(id);
                cs.setServiceId(sc);
                CustomerController custom=new CustomerController();
                int done=custom.doInsert(cs);
                if(done!=0){
                    JOptionPane.showMessageDialog(null, "New Customer Created");
                      this.dispose();   
                }
                else{
                     JOptionPane.showMessageDialog(null, "No Customer Created");
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(StaffSelector.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }
        
    }//GEN-LAST:event_btn_assignActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_assign;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_staff;
    // End of variables declaration//GEN-END:variables

}
